### ISSUE TITLE
No result returned

### ISSUE THREAD

**Issue by cjmyers** [MyersResearchGroup/SynBioSuite#4]
Conversion and simulation of the attached SBOL file returns no data other than time.

[Inverter.zip](https://github.com/MyersResearchGroup/SynBio-Suite/files/9905173/Inverter.zip)

**Comment by zachsents** [comment]
Both this issue and Issue #5 share the same cause. There are two halves to the problem:

1st half: Canvas is omitting ComponentDefinitions from exported SBOL for some reason. It probably has to do with the MxToSBOL converter, which I'll need to investigate further.

2nd half: After repairing the SBOL files manually, the simulations failed. iBioSim API didn't know what to do if more than one SBML file was produced, but there was no topModel.xml or *_topModule.xml file. This case is now being handled as of [this commit](https://github.com/MyersResearchGroup/iBioSim-API/commit/b3ed030d274c847a725a91f810dc76088a2f3907).
